### PR TITLE
GHC-179: Lab tests concepts split across sample types + Lab test form refactored accordingly.

### PR DESCRIPTION
**Pull request by nuhuhmutebi**
This PR implemented the following:
1. Split the lab tests concepts shared between sample types (Gonorrhea, Chlamydia, Bacteria) into multiple concepts. The original concepts were kept for Blood (Gonorrhea, Chlamydia) and Urine (Bacteria) accordingly and the new concepts for Urine and Swab accordingly. This was done to avoid the unnecessary migration.
2. Finally the lab form was rebuilt to reflect the changes implemented above.

Find the link to the corresponding ticket https://mekomsolutions.atlassian.net/browse/GHC-179

### CODE REVIEW

**Review by Ruhanga — COMMENTED** [review]
Hi @nuhuhmutebi, I get [this error](https://pastebin.com/raw/gFPCeXak) when I run these changes against a ghc backup. Have you faced the same and if so could you fix it?

I get this:

Screenshot 2023-07-18 at 12 33 35

**Comment by rbuisson** [comment]
@Ruhanga , that is something I've never seen. Is this only showing when running with the prod database? Or also when running empty?

**Comment by Ruhanga** [comment]
@rbuisson, it turns out that building the search index fixes the issue (red popup error). But then I loose the changes on this PR simply because the config loading is failing on the changes introduced.

**Comment by rbuisson** [comment]
OK. @Ruhanga  @nuhuhmutebi  what's the next course of action then?

**Comment by Ruhanga** [comment]
I'm awaiting @nuhuhmutebi's fix on the part of fixing the failing concept configurations.

**Review by Ruhanga — APPROVED** [review]

**Comment by nuhuhmutebi** [comment]
This PR implemented the following:
1. Split the lab tests concepts shared between sample types (Gonorrhea, Chlamydia, Bacteria) into multiple concepts. The original concepts were kept for Blood (Gonorrhea, Chlamydia) and Urine (Bacteria) accordingly and the new concepts for Urine and Swab accordingly. This was done to avoid the unnecessary migration.
2. Finally the lab form was rebuilt to reflect the changes implemented above.

**Pull request merged**
